 # Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

# Parse JSON documents
pod 'JSONModel'

# timers with blocks
pod 'NSTimer-Blocks'